export const metadata = {
  title: 'About | Create Next App',
  description: 'Generated by create next app',
}

export default async function About() {
  // throw new Error('Test error')
  return (
    <>
      <h1>About page!</h1>
    </>
  )
}
