import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="page">
        <header className="page-header">
          <div className="container">
            <nav className="page-nav">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/tool">Tool</Link>
            </nav>
          </div>
        </header>
        <main className="page-main">
          <div className="container">{children}</div>
        </main>
        <footer className="page-footer">
          <div className="container">
            <p>Footer here</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
