import CSSForm from '../components/Form'

export const metadata = {
  title: 'Tool | Create Next App',
  description: 'Generated by create next app',
}

export default async function Tool() {
  // throw new Error('Test error')
  return (
    <>
      <h1 className="text-4xl leading-12">Tool page!</h1>
      <CSSForm />
    </>
  )
}
